VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|

    if VAGRANT_COMMAND == "ssh"
      config.ssh.username = 'vagrant'
    end
    config.vm.box = "ubuntu/bionic64" # Chọn box bạn muốn sử dụng

    # Khởi tạo máy ảo thứ nhất
    config.vm.define "machine1" do |machine1|
    machine1.vm.network "private_network", ip: "192.168.56.2"
    machine1.vm.provider "virtualbox" do |vb|
          vb.memory = "2048" # 2GB RAM
          vb.cpus = 1       # 1 core CPU
        end

    machine1.vm.provision "shell", inline: <<-SHELL
          adduser trino
          usermod -aG sudo trino
          echo trino ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/trino
        SHELL
    end
    # cai cho /etc/sudoers.d/trino dat ten la gi cung dc, tham chi apeend vao file da co thi cx oke

    # Khởi tạo máy ảo thứ hai
    config.vm.define "machine2" do |machine2|
    machine2.vm.network "private_network", ip: "192.168.56.3"
    machine2.vm.provider "virtualbox" do |vb|
          vb.memory = "2048" # 2GB RAM
          vb.cpus = 1       # 1 core CPU
        end

    machine2.vm.provision "shell", inline: <<-SHELL
          adduser trino
          usermod -aG sudo trino
          echo trino ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/trino
        SHELL
    end
end



