version: '3'

services:
  ### OBSERVABILITY APPS ###
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/datasources/dashboard.yaml
    env_file:
      - ./grafana/.env
    depends_on:
      - prometheus

  app:
    image: longpt233/app-prometheus:latest
    build:
      context: ./app
      dockerfile: ./Dockerfile   # path nay se chuyen ve context/path
    restart: always
    ports:
      - 8081:8081
