VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|

    if VAGRANT_COMMAND == "ssh"
      config.ssh.username = 'vagrant'
    end
    config.vm.box = "ubuntu/bionic64" # Chọn box bạn muốn sử dụng

    # Khởi tạo máy ảo thứ nhất
    config.vm.define "machine1" do |machine1|
    machine1.vm.network "private_network", ip: "192.168.56.10"
    machine1.vm.provider "virtualbox" do |vb|
          vb.memory = "1024" # 2GB RAM
          vb.cpus = 1       # 1 core CPU
        end

    machine1.vm.provision "shell", inline: <<-SHELL
          sudo apt update && sudo apt upgrade -y
          sudo apt install curl gnupg -y
          curl -fsSL https://packages.rabbitmq.com/gpg | sudo apt-key add -
          sudo add-apt-repository 'deb https://dl.bintray.com/rabbitmq/debian focal main'
          sudo apt update && sudo apt install rabbitmq-server -y
          sudo systemctl enable rabbitmq-server
          sudo systemctl start rabbitmq-server
          sudo rabbitmq-plugins enable rabbitmq_management
        SHELL
    end
end