global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: app
    metrics_path: /metrics
    static_configs:
      - targets:
          - "app:8081"
        labels:
          app: webapi